// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var welcome = Welcome.FromJson(jsonString);

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var welcome = Welcome.FromJson(jsonString);

namespace RoomsToTopoJson
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.IO;



    //public partial class Welcome
    //{
    //    [JsonProperty("type")]
    //    public string Type { get; set; }

    //    [JsonProperty("transform")]
    //    public Transform Transform { get; set; }

    //    [JsonProperty("objects")]
    //    public Objects Objects { get; set; }

    //    [JsonProperty("arcs")]
    //    public List<List<List<long>>> Arcs { get; set; }
    //}

    //public partial class Objects
    //{
    //    [JsonProperty("two-squares")]
    //    public TwoSquares TwoSquares { get; set; }
    //}

    //public partial class TwoSquares
    //{
    //    [JsonProperty("type")]
    //    public string Type { get; set; }

    //    [JsonProperty("geometries")]
    //    public List<Geometry> Geometries { get; set; }
    //}

    //public partial class Geometry
    //{
    //    [JsonProperty("type")]
    //    public string Type { get; set; }

    //    [JsonProperty("arcs")]
    //    public List<List<long>> Arcs { get; set; }

    //    [JsonProperty("properties")]
    //    public Properties Properties { get; set; }
    //}

    //public partial class Properties
    //{
    //    [JsonProperty("name")]
    //    public string Name { get; set; }
    //}

    //public partial class Transform
    //{
    //    [JsonProperty("scale")]
    //    public List<long> Scale { get; set; }

    //    [JsonProperty("translate")]
    //    public List<long> Translate { get; set; }
    //}

    //public partial class Welcome
    //{
    //    public static Welcome FromJson(string json) => JsonConvert.DeserializeObject<Welcome>(json, RoomsToTopoJson.Converter.Settings);
    //}

    //public static class Serialize
    //{
    //    public static string ToJson(this Welcome self) => JsonConvert.SerializeObject(self, RoomsToTopoJson.Converter.Settings);
    //}

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    public class export
    {
        public static void serializeJason(Rootobject JsonInfo, string fileLocation)
        {
            string json = JsonConvert.SerializeObject(JsonInfo, RoomsToTopoJson.Converter.Settings);

            using (StreamWriter file = File.CreateText(fileLocation))
            {
                JsonSerializer serializer = new JsonSerializer();
                serializer.Serialize(file, JsonInfo);
            }
        }
    }
}



//public class Rootobject
//{
//    public string type { get; set; }
//    public Transform transform { get; set; }
//    public Objects objects { get; set; }
//    public double[][][] arcs { get; set; }
//}

//public class Transform
//{
//    public int[] scale { get; set; }
//    public int[] translate { get; set; }
//}

//public class Objects
//{
//    public TwoSquares twosquares { get; set; }
//}

//public class TwoSquares
//{
//    public string type { get; set; }
//    public Geometry[] geometries { get; set; }
//}

//public class Geometry
//{
//    public string type { get; set; }
//    public int[][] arcs { get; set; }
//    public Properties properties { get; set; }
//}

//public class Properties
//{
//    public string Department { get; set; }
//}



public class Rootobject
{
    public string type { get; set; }
    public Feature[] features { get; set; }
}

public class Feature
{
    public string type { get; set; }
    public Properties properties { get; set; }
    public Geometry geometry { get; set; }
}

public class Properties
{
}

public class Geometry
{
    public string type { get; set; }
    public float[][][] coordinates { get; set; }
}
